### ISSUE TITLE
15 New Artkal Colors (2023)

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadifier#103]
Hey, hope you've been doing well!

This year, Artkal released 15 new colors for their S-Series Beads. I've put together all the colors, codes and numbers below (Always huge credit to the PerlyPop App for having this information!)

Here's the information below:

#F1F4FA - R: 241 G: 244 B: 250 - SE1 - Moon
#A2B2D3 - R: 162 G: 178 B: 211 - SE2 - Raincloud
#83A6DC - R: 131 G: 166 B: 220 - SE3 - Winter
#70D8ED - R: 112 G: 216 B: 237 - SE4 - Tide
#69E3D5 - R: 105 G: 227 B: 213 - SE5 - Aquamarine
#2A63C8 - R: 042 G: 099 B: 200 - SE6 - Neptune
#D5AEC9 - R: 213 G: 174 B: 201 - SE7 - Rose Quartz
#AF739A - R: 175 G: 115 B: 154 - SE8 - Mauve
#704B6D - R: 112 G: 075 B: 109 - SE9 - Dark Mauve
#D977CD - R: 217 G: 119 B: 205 - SE10 - Wild Berry
#B643AC - R: 182 G: 067 B: 172 - SE11 - Sugar Plum
#DEB181 - R: 222 G: 177 B: 129 - SE12 - Desert
#BC9D77 - R: 188 G: 157 B: 119 - SE13 - Peanut
#AC7F5D - R: 172 G: 127 B: 093 - SE14 - Toffee
#A37E66 - R: 163 G: 126 B: 102 - SE15 - Bark

**Comment by maxcleme** [comment]
Wow! I'll have a look right now!

**Comment by maxcleme** [comment]
As always, many thanks @Exodeca1 for your continuous support! 🙇
