### ISSUE TITLE
Petites questions de ch'nord ;)

### ISSUE THREAD

**Issue by JOHAAANNS** [maxcleme/beadifier#104]
Bonjour,

Ma femme découvre votre logiciel et vous en remercie+++ il est excellent!
Il est parfait pour l'utilisation de transformation d'une image en perles. 

En revanche elle avait deux questions :

Si elle a déjà un modèle en perles, est-il possible:
- De ne pas le transformer mais de juste quantifier le nombre et connaître les références couleurs des perles ?
- D'avoir la possibilité de le réduire ou l'agrandir ?
 (Pour ma part je pense que ce n'est pas possible, mais bon ;)  Ma femme tiens à ce que je note ces questions ! )

Merci beaucoup pour votre retour et pour tout le travail fait !

Johannes
(Je ne sais pas si c'est bien ici que je dois poser ce genre de remarque ;) )

**Comment by maxcleme** [comment]
Hello,

Hélas je ne vois pas vraiment comment on pourrait faire. Pour tirer le trait, même en partant d'une photo réel du projet `beadifier` ne ferait pas la distinction entre la table et les perles 😅 (faites l'expérience en prenant en photo votre projet !)

Merci pour le soutien, content que l'outil vous plaise ! 😁

**Comment by JOHAAANNS** [comment]
Merci Maxclem pour votre réponse ;)
Bon courage ;)
