### ISSUE TITLE
taille planche perles

### ISSUE THREAD

**Issue by Thecrazygirl68** [maxcleme/beadifier#106]
Bonjour, 

Il faudrait modifier la taille des planches. 
Je ne sais pas a quoi corresponds la taille 50*50 pour les mini . 

les planches que j'ai acheter font 14.5*14.5 pour les mini perles de 2.6mm .

il faudrait vérifier la taille des planche sur diffèrent site.

**Comment by maxcleme** [comment]
Les taille sont en nombre de perles et non en mm

**Comment by Thecrazygirl68** [comment]
Oh d’accord , je vois merci.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : maxcleme ***@***.***>
Envoyé : Monday, September 9, 2024 8:56:15 AM
À : maxcleme/beadifier ***@***.***>
Cc : Thecrazygirl68 ***@***.***>; Author ***@***.***>
Objet : Re: [maxcleme/beadifier] taille planche perles (Issue #106)


Les taille sont en nombre de perles et non en mm
