### ISSUE TITLE
Perler color # name too long

### ISSUE THREAD

**Issue by sunshin89** [maxcleme/beadifier#17]
When making the pattern everything is great! Use this site all the time. Tried to use today and once I click export and look at the pattern, you can figure out which color is what as the numbers for the colors have changed from P01 to 80-19001 which is too long per square to know which color is what when making the pattern! Please fix this! The other way was so much better!

**Comment by maxcleme** [comment]
Good point, I updated all color references to target an other repository which aims to maintains the whole palette, however the references for Perler brand are not the same anymore.

Should be fix today, thanks a lot for pointing out my mistake !

**Comment by maxcleme** [comment]
@sunshin89 should be fixed and online, I'll let you confirm and close this issue if everything is OK for you :)

Thanks again!

**Comment by sunshin89** [comment]
Thank you!!!!! It’s now works!!
