### ISSUE TITLE
No way to reset Usage setting

### ISSUE THREAD

**Issue by Remittingdust** [maxcleme/beadifier#23]
Once pressing the 1% button on the usage tab - there is no way to reset to origional setting, or undo clicking on the button. 

This means that if the user clicks the button and doesn't like what it has done, they have to start all over with importing their picture. 

![image](https://user-images.githubusercontent.com/63864847/79586059-a2a2fc80-809e-11ea-847a-bc1fbb6b6816.png)

**Comment by maxcleme** [comment]
You're absolutely right! Going to look at this during next week, I'll keep you in touch.

Thanks again for feedback

**Comment by maxcleme** [comment]
@Remittingdust , I added a "Undo" button in the "Usage" tab !

Can you take few minute to check if everything is fine for you ? If so, feel free to close the issue :)

**Comment by Remittingdust** [comment]
Perfect! Thanks for the fix :)
