### ISSUE TITLE
Excel export and exact pixel size

### ISSUE THREAD

**Issue by lindehell** [maxcleme/beadifier#27]
Just wondering if the Excel export option will still be around. It has been invaluable to me in my work. 

Also is fit to board the new normal? Will you be able to set size manually as well?

**Comment by maxcleme** [comment]
Hi, thanks for submitting an issue, however I don't understand your point.

Excel export was never implemented, do you mean that's something you would
like to?

Regarding the 'fit to board' option, it's the default behavior since the
beginning, however someone raise an issue regarding this when using a image
smaller than the board. That's why you can now disable it to use what we
could called '1px = 1 bead'.

Feel free to give more details if I'm mistaken on one of those two topics.

**Comment by lindehell** [comment]
Turns out I'm mixing up beadifiers. But I really like what you are doing here. 

I used to work with an app that had Excel export. Where the cells were colored in the right tone and of course also hade the text. I really liked being able to move using the arrow keys so I never got lost. Also Excel has the text-to-speach function so I never had to look at the screen at all which is a timesaver for bigger projects. It could be implemented alongside the PDF which I guess is the best for most users. What do you think? 

Regarding the total pixel size. Forget it. Fit to board is great.

Sorry for the confusion. You are doing great work!

**Comment by maxcleme** [comment]
No worries,

Excel export could be a thing, I just need to look at the format in order
to see if it's doable, would also look at ODF in order to have a free
alternative

**Comment by lindehell** [comment]
Sounds great

**Comment by maxcleme** [comment]
@lindehell , this feature is still planned, however I started to work again (professionally speaking), so it might take more time than I expected since I got less free time :sweat_smile:

**Comment by maxcleme** [comment]
@lindehell 

I've been playing a bit with Excel export.

I came up with something like this, could you please check if everything's fine on your side ? (I don't have Excel unfortunately but it opens seamlessly with LibreOffice Calc).

[beadifier_test.zip](https://github.com/maxcleme/beadifier/files/4931372/beadifier_test.zip)
(I had to zip it so I could upload the file here)

I still need to figure out how to : 
+ Make an second tab displaying beads inventory
+ Set border of each boards

Cheers!

**Comment by maxcleme** [comment]
Implemented in v1.14.0.
