### ISSUE TITLE
Reset all the options?

### ISSUE THREAD

**Issue by knives007** [maxcleme/beadifier#30]
Hello, I´m starting to use this software, in my opinion it is one of the best I found (maybe the best) and I am very happy with the author, but can you add an option to reset all the latest settings or get the original options ? ? that's because when I reload or refresh the browser because I don't like some changes in the USAGE option, the software doesn't reset the last changes, and now I need to switch to another browser to get the original options, at least in the USAGE option, this is very important because this option changes all the colors

THX so much for the attention

**Comment by maxcleme** [comment]
Hi, thanks for taking your time to report an issue/feature request here.

A reset button shouldn't be too hard to do, I'll add it to my to-do list,
that's a good idea!

However I'm kinda curious about you said, there is currently no persistence
at all in this application so it is technically impossible for the usage
tab to stay the same when you reload the page. 🤔

Maybe you could come up with some details step to reproduce the wrong
behavior?

**Comment by maxcleme** [comment]
@knives007 ping for update.
