### ISSUE TITLE
What about combining brands

### ISSUE THREAD

**Issue by dpalay** [maxcleme/beadifier#32]
While Hama & Nabbi don't mix with the others, Artkal and Perlers can be used together pretty seamlessly (pun intended, after ironing).    If I have both Perler beads and Artkal beads, I'd love to be able to choose BOTH for better color matching.

**Comment by maxcleme** [comment]
Hi,

Thanks for opening issue, however you should already be able to select multiple brand at once.

![image](https://user-images.githubusercontent.com/7669401/85028022-dec80b80-b17a-11ea-9e6d-94db56a0bf19.png)

Is it something not working properly on your side ?

**Comment by dpalay** [comment]
Huh.  I must have been on an older version? 
![image](https://user-images.githubusercontent.com/33780/85028934-58db9e80-b141-11ea-9e80-3cbd275dbe78.png)


Refreshed the page and I'm seeing the configuration options now.

**Comment by maxcleme** [comment]
Might have been cache issue, sorry for inconvenience.

**Comment by dpalay** [comment]
No worries.  Btw, I assume some of the colors for this came from the LThanda spreadsheet?  Cause that's me! :D

**Comment by maxcleme** [comment]
@dpalay 

![](https://media.giphy.com/media/5VKbvrjxpVJCM/giphy.gif)

Of course I used from of your values ! Thanks for this awesome work !

All colors references here are based on another [repository](https://github.com/maxcleme/beadcolors), which merge 3 or 4 main spreadsheets I found around the web. I tends to use the more recent one as reference, so few of your colors has been discarded for others.
