### ISSUE TITLE
PDF UTF8 Symbol not rendered

### ISSUE THREAD

**Issue by maxcleme** [maxcleme/beadifier#44]
When using symbol feature, some symbol are not rendered in the exported PDF.

Might be related to utf8 symbol that comes when palette has many entries (diamond).

**Comment by maxcleme** [comment]
@jaymeh Any idea how we could handle this ? I didn't look into jsPDF setting yet, but it seems UTF8 is not well/yet supported anyway

**Comment by jaymeh** [comment]
@maxcleme - So it could be that the font doesn't support specific symbols.

https://github.com/MrRio/jsPDF/issues/1906

I'm wondering if it's going to take some testing with different fonts in order to see which ones support the symbols we have.

**Comment by maxcleme** [comment]
@jaymeh might be right.

I'm building all thing with https://github.com/maxcleme/beadifier/pull/42 incorporates. I set the font the Roboto Mono in order to manage dynamic font (since each char is the same width, it is way easier), then I also have to packed to font in the pdf in order to have it offline (with the base64 tricks).

I'm planning to release both #41 and #42  together today anyway. 

At least we are aware of a bug, we "only" need to fix it now :sweat_smile:

**Comment by jaymeh** [comment]
Perfect, ok. If you have an example you tried with to replicate this issue I don't mind having a quick look at it and playing with a few things on it.

**Comment by maxcleme** [comment]
@jaymeh Sure, I use the following picture with diamond palette (master branch).

master branch should be in online pretty soon.

Note: Everything goes well with SVG which use the same trick in order to embed the font, it's a bit different but the font is the same, Roboto Mono.

![Philips_PM5544 svg](https://user-images.githubusercontent.com/7669401/90247440-da486800-de36-11ea-92ec-8af6cbfa495f.png)

**Comment by jaymeh** [comment]
@maxcleme mm this isn't ideal. I've noticed a small few issue with the colour spreadsheet surrounding the ; character. I plan on removing this from the list.

https://stackoverflow.com/questions/21923488/how-to-enable-utf-8-in-jspdf-library - This doesn't look good for us. Seems that there isn't full UTF8 support in jsPDF. Didn't account for this during the initial testing. The only current solution is to render text using canvas and push it into the pdf but this creates text that doesn't look good at all.

THere are a few other libraries that support this feature also. I'm not sure if you have managed to find anything on this?

**Comment by maxcleme** [comment]
@jaymeh didn't really started to look at it, but I'll will.

**Comment by jaymeh** [comment]
@maxcleme Ok, sorry I just thought it was worth you having a quick look also. If we find an alternative way of getting it to work or see no other option than to switch to a different method/library to parse. I'd be happy to pick this up since I effectively have caused this issue but I just wanted to give you the chance to see if there was anything I might have missed. Keep in touch with what you find out anyway and I'll wait for your decision 👍

**Comment by maxcleme** [comment]
@jaymeh yup, don't worry we will find a workaround to make it work, no doubt 😉

**Comment by maxcleme** [comment]
@jaymeh 

After testing a lots of Fonts, it looks I found one suitable candidate. I mock a fake usage in order to have one bead for each references of diamond dots palette. I still needs to tweak dynamic size constant in order to make it works everywhere but at least it worked.

[beadifier_2x2 (28).pdf](https://github.com/maxcleme/beadifier/files/5096002/beadifier_2x2.28.pdf)

**Comment by jaymeh** [comment]
@maxcleme Nice work, this is amazing news! I must admit I was a bit stumped by the issue initially. If you need any assistance with testing or code changes, give me a shout 😃 .

**Comment by maxcleme** [comment]
Fix in v1.13.0

I really need to set up some integration/e2e testing in order to validate all of this with github actions.
