### ISSUE TITLE
Board Reference Missing from PDF

### ISSUE THREAD

**Issue by jaymeh** [maxcleme/beadifier#51]
Seems that board reference numbers are missing from PDF files at the top of each page See attached for an example. Is this as designed @maxcleme ?

If this is a bug, I'm quite happy to take a quick look and submit a PR to fix. Cheers!

[beadifier_2x1 (2).pdf](https://github.com/maxcleme/beadifier/files/5196625/beadifier_2x1.2.pdf)

**Comment by maxcleme** [comment]
You are absolutely right, looks like we got some breaking changes during redoing all of these 'printers'. Nice catch!

**Comment by jaymeh** [comment]
Thought it may have been related. No worries @maxcleme I'll have a look
into it later. 👍

**Comment by maxcleme** [comment]
@jaymeh Thanks for fixing it, I'm going to deploy new version tomorrow (I'm not home right now), don't be scared to notify me if it's not up and running by then.

Cheers!

**Comment by maxcleme** [comment]
Deployed and fixed in v1.15.1.
