### ISSUE TITLE
Number input for Brightness, Contrast etc.

### ISSUE THREAD

**Issue by lindehell** [maxcleme/beadifier#53]
I do most of my patterns on my phone and the sliders in the advanced window are hard to finely adjust. I suggest a text box beside it where Brightness, Contrast and saturation go someting like -50, 0, -50 and grayscale and dithering from 0 to 100

If I loose the pattern or wanna go back and fine-tune something, having the option to precisely enter these parameters would be great for reproducibility

What do you think?

**Comment by maxcleme** [comment]
@lindehell It is really a good idea !

I'll put this one in my backlog, even if I'm going to work on a save/load presets feature beforehand I think :) 

(which could also fix your issue)

**Comment by maxcleme** [comment]
@lindehell 

What do you think of something like this ? 

![image](https://user-images.githubusercontent.com/7669401/96336834-83534f00-1082-11eb-9da1-f3908cb608f0.png)

**Comment by maxcleme** [comment]
@lindehell 

Slider input has been added in v1.20.0.

**Comment by lindehell** [comment]
Totally missed rhis, this looks amazing!

**Comment by maxcleme** [comment]
@lindehell Feel free to close or come up with some feedback :wink:

**Comment by lindehell** [comment]
I am not great at this gitting thing. I love it!
