### ISSUE TITLE
Delta E version/tweaking

### ISSUE THREAD

**Issue by lindehell** [maxcleme/beadifier#61]
Hi, me again

I've found it curious that the Delta E color matching in my opinion makes weird calls sometimes. What version of the  CIE dE formula is being implemented? There has been so much progress in this field since the 1976 version.

I know I'm being a huge nerd now, but might it be worth checking it out or at least playing around with some weights?

/Your greatest fan

**Comment by maxcleme** [comment]
@lindehell 

TBH it's been a while since I have implemented the DeltaE Matching.

Feel free to look at the source here : https://github.com/maxcleme/beadifier/blob/master/src/app/model/matching/matching.model.ts#L22

**Comment by maxcleme** [comment]
@lindehell 

Looks like CIE94 : https://en.wikipedia.org/wiki/Color_difference#CIE94

**Comment by lindehell** [comment]
Sure looks like the 94 one. Which is great, but would it even be an option to try the 2000 version? When running it on my phone the DeltaE takes a bit of time for larger designs. I'd be willing to try it out in my patternmaking and give feedback , if you put it in (it's a monster of a equation but I think you could benefit from it in green/gray regions and in the very light). You could have it as a third beta option. This is now the only tool I use, you are doing great work

**Comment by maxcleme** [comment]
Could definitely be implemented as a third option. But I don't know when to
be honest 😅

**Comment by lindehell** [comment]
I just think it's great that you listen to feedback. If or when you feel like it.

As it it now I have learnt some of the weaknesses and do some either on-the-fly editing or I go over it after, but it's very time consuming 

Let me know if/when and I'll test the shit out of it

**Comment by maxcleme** [comment]
@lindehell I have to admit I couldn't resist to give it a try.

I spend some time tweaking it, looks like I've come up with something compliant with the test results provided by G.Sharma itself : 

http://www2.ece.rochester.edu/~gsharma/ciede2000/


**Original Image**
![colors](https://user-images.githubusercontent.com/7669401/98704977-88ec3e00-237d-11eb-84da-5d332de7a462.jpg)


**Euclidean**
![eucliean](https://user-images.githubusercontent.com/7669401/98705150-b0dba180-237d-11eb-9b73-9c545b035d7d.png)

**Delta E (CIE94)**
![94](https://user-images.githubusercontent.com/7669401/98705163-b3d69200-237d-11eb-8345-79519f270637.png)

**Delta E (CIE2000)**
![2000](https://user-images.githubusercontent.com/7669401/98705173-b76a1900-237d-11eb-9302-847e751720c8.png)


I still have to fix few things before creating the MR/Merge/Deployment.

I'll keep you in touch once deployed in production.

**Comment by maxcleme** [comment]
@lindehell 

Up and running with v1.21.0

![image](https://user-images.githubusercontent.com/7669401/98710357-d23f8c00-2383-11eb-8337-24ad8cd613a5.png)

I'll you play with it and comeback with additional feedbacks, feel free to close directly if everything is fine :)

**Comment by lindehell** [comment]
Wow, I love it. Like I thought it fixed the gray green transition right out of the box. Looks amazing! I'll close it because all the patterns I made with it so far looks great. If there is anything wrong still it will be seen in the translation to plastic (and then would most likely be an RGB error). Can't wait to use it!

You are amazing, thank you 💜
