### ISSUE TITLE
Select all from individual pallettes

### ISSUE THREAD

**Issue by lindehell** [maxcleme/beadifier#65]
It would be a huge timesaver if there was an select/deselect all slider for **each** active palette. The one that's there for all palettes could still be at the top.

I mix Hama and Artkal a lot and it has been bugging me and a colleague that this isn't an option.

Thanks again for listening and delivering a great product

**Comment by maxcleme** [comment]
@lindehell Great feedback, I'll look at it.

**Comment by maxcleme** [comment]
@lindehell 

Available in v1.23.0.

**Comment by lindehell** [comment]
My god you work fast

Thank you
