### ISSUE TITLE
Missing Colors - Apols did try commenting on closed issue but new to github and trying to figure it all out :)

### ISSUE THREAD

**Issue by RetrolixusMcD** [maxcleme/beadifier#79]
Hey There,

first off, amazing program, i used to use hobby.dk and thought i would be at a loss without it when it closed but your beadifier program is amazing!
colour wise there are the following hama ones missing from the list, is there a way to add them either myself or in general? is it an issue with the RGB where they are chrome etc?

H15 - TRANSPARENT BLUE
H55 - GLOW IN THE DARK GREEN
H56 - GLOW IN THE DARK RED
H57 - GLOW IN THE DARK BLUE
H61 - GOLD
H62 - SILVER
H63 - BRONZE
H64 - PEARL
H72 - TRANSLUCENT PINK
H73 - TRANSLUCENT AQUA
H74 - TRANSLUCENT AQUA

thanks

Danny McD

**Comment by maxcleme** [comment]
@RetrolixusMcD 

Thanks for reaching me out, I'll close this issue in favor of https://github.com/maxcleme/beadcolors/issues/33.

Sorry for being late to answer. I'll update the issue asap.

Cheers.
