### ISSUE TITLE
3 New Perler Colors

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadifier#93]
There are 3 new Perler Colors recently released, please see the values below. As before, they come from the PerlyPop app which has been very accurate with colors!

#C685B1 - R: 198 G: 133 B: 177 - P265 - Twilight Plum
#6CC8AD - R: 108 G: 200 B: 173 - P266 - Caribbean Sea
#CDB7C3 - R: 205 G: 183 B: 195 - P267 - Frosted Lilac

**Comment by Exodeca1** [comment]
Sorry to be a bother! Just wanted to know if there was an update or anything additional I could provide.

**Comment by maxcleme** [comment]
@Exodeca1 They are now available!

**Comment by Exodeca1** [comment]
> @Exodeca1 They are now available!
Awesome! I see them available =) Thank you so much! Hope you're doing great! =)
